[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/Fronttest.pem
ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/.ssh/Fronttest.pem -W %h:%p ubuntu@10.112.2.65" -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[master_bkk]
10.0.0.3

[master_non]
10.0.0.9

[workers_bkk]
10.0.0.8
10.0.0.2

[workers_non]
10.0.0.6
10.0.0.4

[argocd]
10.0.0.5

[lb]
10.0.0.7

# === logical groupings for the playbook ===
[masters:children]
master_bkk
master_non

[workers:children]
workers_bkk
workers_non

[all_nodes:children]
masters
workers
argocd
lb
